name: Build

on:
  push:
  schedule:
  # 定时任务
    - cron: '0 */1 * * *'
jobs:
    build:
        name: Build candy
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: Setup Node.js environment
          uses: actions/setup-node@v2.1.4
        - name: Candy Install
          run: yarn
        - name: Build Out Candy
          run: yarn build
        - name: Upload Candy Build Artifact
          uses: actions/upload-artifact@v2.2.2
          with:
            name: Out
            path: ./out
