name: candy Build

on: [push]

jobs:
    build:
        name: Build candy
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: Setup Node.js environment
          uses: actions/setup-node@v2.1.4
        - name: Candy Install
          run: yarn
        - name: Build Out Candy
          run: yarn build
        - name: Upload Candy Build Artifact
          uses: actions/upload-artifact@v2.2.2
          with:
            name: Out
            path: ./out
    build-server:
        name: Build Mix-Space(server)
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: Setup Node.js environment
          uses: actions/setup-node@v2.1.4
        - name: Install rimraf
          run: |
            sudo npm install rimraf -g
        - name: Clone and Install
          run: |
            git clone https://github.com/mx-space/server
            cd server
            sudo yarn
        - name: fix user files
          run: |
            rm -rf .env
            wget http://api.iucky.cn/themes/.env_server
            mv .env_server .env
            echo "fix user files success"
        - name: yarn build
          run: sudo yarn build
        - name: Upload server Build Artifact
          uses: actions/upload-artifact@v2.2.2
          with:
            name: server
            path: ./server
    build-kami:
        name: Build Mix-Space(kami)
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: Setup Node.js environment
          uses: actions/setup-node@v2.1.4
        - name: Install rimraf
          run: |
            sudo npm install rimraf -g
        - name: Clone and Install
          run: |
            git clone https://github.com/mx-space/kami
            cd kami
            sudo yarn
        - name: fix user files
          run: |
            rm -rf .env
            rm -rf config.ts
            wget http://api.iucky.cn/themes/kami/.env
            wget http://api.iucky.cn/themes/kami/configs.ts
            cd public
            rm -rf manifest.json
            wget http://api.iucky.cn/themes/kami/public/manifest.json
            cd ..
            echo "fix user files success"
        - name: yarn build
          run: sudo yarn build
        - name: Upload kami Build Artifact
          uses: actions/upload-artifact@v2.2.2
          with:
            name: kami
            path: ./kami
    build-admin:
        name: Build Mix-Space(admin)
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: Setup Node.js environment
          uses: actions/setup-node@v2.1.4
        - name: Build admin
          run: |
            git clone https://github.com/mx-space/admin
            sudo npm install rimraf -g
            cd admin
            sudo yarn
            sudo rm -rf .env
            sudo rm -rf vue.config.js
            sudo wget http://api.iucky.cn/themes/admin/.env
            sudo wget http://api.iucky.cn/themes/admin/vue.config.js
            echo "fix user files success"
            sudo yarn build
        - name: Upload admin Build Artifact
          uses: actions/upload-artifact@v2.2.2
          with:
            name: admin
            path: ./admin/dist
