name: Build

on:
  push:
  schedule:
  # 定时任务
    - cron: '0 * * * *'
jobs:
    build:
        name: Build candy
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: Setup Node.js environment
          uses: actions/setup-node@v2.1.4
        - name: Candy Install
          run: yarn
        - name: Build Out Candy
          run: yarn build
        - name: Upload Candy Build Artifact
          uses: actions/upload-artifact@v2.2.2
          with:
            name: Out
            path: ./out
        - name: tar file
          run: |
            tar cf Out.tar.gz out
            sudo rm -rf .next
            sudo rm -rf out
            sudo rm -rf node_modules
        - name: Create a Release
          uses: actions/create-release@v1.1.4
          with:
            tag_name: Release By Bot
            release_name: Out
            body: Candy performance
            owner: wibus-wee
            repo: Mix-Space-ACTION
            token: ${{ secrets.GITHUB_TOKEN }}
        - name: delete tar file
          run: |
            sudo rm -rf Out.tar.gz
        - name: Git Commit and Push
          uses: github-actions-x/commit@v2.6
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: Bot Build
            email:  1596355173@qq.com
            name: wibus-wee
            
