name: Build

on:
  push:
  schedule:
  # 定时任务
    - cron: '0 * * * *'
jobs:
    build:
        name: Build candy
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: Setup Node.js environment
          uses: actions/setup-node@v2.1.4
        - name: Candy Install
          run: yarn
        - name: Build Out Candy
          run: yarn build

        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./out
