name: candy Build

on: [push]

jobs:
    build:
        name: Build candy
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: Setup Node.js environment
          uses: actions/setup-node@v2.1.4
        - name: Candy Install
          run: yarn
        - name: Build Out Candy
          run: yarn build
        - name: Upload Candy Build Artifact
          uses: actions/upload-artifact@v2.2.2
          with:
            name: Out
            path: ./out
    build-server:
        name: Build server
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: Setup Node.js environment
          uses: actions/setup-node@v2.1.4
        - name: Server clone
          run: git clone https://github.com/mx-space/server
        - name: Install rimraf
          run: |
            yarn global add pm2 -g
            yarn global add ts-node -g
            sudo npm install rimraf -g
            sudo npm install --save-dev cross-env -g
        - name: Server Install
          run: |
            cd server
            cp .env.example .env
            yarn
        - name: Server Build
          run: yarn build
        - name: Upload Candy Build Artifact
          uses: actions/upload-artifact@v2.2.2
          with:
            name: server
            path: ./server
    build-kami:
        name: Build kami
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: Setup Node.js environment
          uses: actions/setup-node@v2.1.4
        - name: kami clone
          run: git clone https://github.com/mx-space/kami
        - name: Install rimraf
          run: sudo npm install rimraf -g
        - name: kami Install
          run: |
            cd kami
            yarn
        - name: kami Build
          run: yarn build
        - name: Upload kami Build Artifact
          uses: actions/upload-artifact@v2.2.2
          with:
            name: kami
            path: ./kami
    build-admin:
        name: Build admin
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: Setup Node.js environment
          uses: actions/setup-node@v2.1.4
        - name: kami clone
          run: git clone https://github.com/mx-space/admin
        - name: Install rimraf
          run: |
            sudo npm install rimraf -g
            sudo npm install --save-dev cross-env -g
        - name: admin Install
          run: |
            cd admin
            yarn
        - name: admin Build
          run: yarn build
        - name: Upload admin Build Artifact
          uses: actions/upload-artifact@v2.2.2
          with:
            name: admin
            path: ./admin/dist
        
