name: candy Build

on: [push]

jobs:
    build:
        runs-on: macOS-latest
        steps:
        - uses: actions/checkout@v2
        - name: install node+yarn
          run: |
            git clone git://mirrors.ustc.edu.cn/homebrew-core.git//usr/local/Homebrew/Library/Taps/homebrew/homebrew-core --depth=1
            brew install yarn
        - name: Test ok
          run: |
            node -v
            npm -v
            yarn -v

